### ISSUE TITLE
About Folder structure & running the script

### ISSUE THREAD

**Issue by mountains-high** [hellog2n/evaluation-medical-imaging#1]
Hello, 
Thank you for your great work!

I want to evaluate gray-scale images(MNIST, FMNIST). 
Could you help me to run the evaluations? 
In order to calculate all the metrics, do images should be under the one folder like ./real and ./fake or
```
./real
           ./0
               001.png
               345.png
           .1/
               900.png
               123.png
          etc.
```
Currently, I'm facing with this issue:
```
Traceback (most recent call last):
  File "run.py", line 155, in <module>
    eval_embeddings, _fakepath = load_or_generate_embedding(
  File "run.py", line 77, in load_or_generate_embedding
    imgs = load_images_from_dir(files, nc)
  File "run.py", line 117, in load_images_from_dir
    dataloader = torch.utils.data.DataLoader(dataset,
  File "/home/user/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 277, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore[arg-type]
  File "/home/user/.local/lib/python3.8/site-packages/torch/utils/data/sampler.py", line 97, in __init__
    raise ValueError("num_samples should be a positive integer "
ValueError: num_samples should be a positive integer value, but got num_samples=0
```
I have another question, if I have 10K images, what would be the best value for nearest_k? 
Thank you. 

P.S: I was able to run your https://github.com/hellog2n/Evaluation-Metric, and got prdc values, while nearest_k values were increased, accordingly, PR values were increased too. What will be theoretical explanation for this behavior? 
I would like to calculate IS, FID, PR, could you assist me please? 
Thank you very much

**Comment by hellog2n** [comment]
Hi! Thank you for your question and I am sorry for my late response. 
(1) I think that the images should better be under the one folder in my current sourcecode.
```
./real
ㄴ 001.png
ㄴ 002.png

./fake
ㄴ 001.png
ㄴ 002.png
```

but you can use your custom dataset. For example, `ImageFolder` provided by Pytorch dataset library seems like to need class folder in parent folder. (sorry for my english)

(2) In Density and Coverage paper, they formulated their k value and explained why we use k value **5** for evaluating. so I think you would better use 5 for k value. However, in improved precision and recall, the author didn't not set a standard about that and they decide the k value to 3 empirically. 

(3) The k-nearest neighbor algorithm is used for estimating manifold of real and fake dataset in feature space. And if the nearest k is increasing, estimated data manifold  may be larger than when smaller k. 

Let's see the precision. Precision is counting the number of fake samples which is in real manifold. If real manifold is larger, the probability of fake sample which is in larger real manifold is more than in smaller real manifold. Recall is counting the number of real samples which is in fake manifold. If fake manifold is larger, the probability of real sample which is in larger fake manifold is more than in smaller fake manifold.

If data have outliers, the manifold might be larger than we expected. So metric could overestimate. 

Density and Coverage solve this problem and others. 

If you want to know about this metrics more, I recommend you read their paper! 


And This source code is out of dated (I think) because the code may have some error logic for evaluating IS.
 I am updating the evaluation framework and protocol for generative models in my project. I will upload it soon. Thank you so much!

**Comment by mountains-high** [comment]
Thank you for your time and consideration. And of course for a detailed explanation. 
I was able to run via putting all the images under the one folder (not class folders)
Thank you ~
